language: node_js
node_js:
  - "6"
  - "5"
  - "4"
before_install:
  - wget -O households.px https://www.pxweb.bfs.admin.ch/DownloadFile.aspx?file=px-x-households
script:
  - node index.js -i households.px -o households.csv

