language: node_js
node_js:
  - "8"
  - "6"
before_install:
  - wget -O households.px https://www.pxweb.bfs.admin.ch/DownloadFile.aspx?file=px-x-0102020000_402
script:
  - node index.js -i households.px -o households.csv

